# Generated by Django 4.0.4 on 2023-02-27 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_domain', models.CharField(max_length=50)),
                ('college_name', models.CharField(help_text='Please capitalize the name', max_length=100)),
                ('state_province', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=2)),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='')),
                ('slug', models.SlugField(blank=True, max_length=110)),
                ('is_approved', models.BooleanField(blank=True, default=False)),
            ],
            managers=[
                ('all_colleges', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='this is the name of the department', max_length=50, unique=True, verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='RequestCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=15, verbose_name='unique ID of the course')),
                ('course_name', models.CharField(max_length=90, verbose_name='name of course')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colleges.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=15, verbose_name='unique ID of the course')),
                ('course_name', models.CharField(max_length=90, verbose_name='name of course')),
                ('slug', models.SlugField(blank=True, max_length=90)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colleges.department')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Possible Departments in College', to='colleges.department'),
        ),
        migrations.AddConstraint(
            model_name='requestcourse',
            constraint=models.UniqueConstraint(fields=('college', 'department', 'course_name', 'course_id'), name='req_course_alt_key'),
        ),
        migrations.AddConstraint(
            model_name='requestcourse',
            constraint=models.UniqueConstraint(fields=('course_id',), name='secondary_course_id_key_request_course'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('college', 'department', 'course_name', 'course_id'), name='college_course_alt_key'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course_id',), name='secondary_course_id_key'),
        ),
        migrations.AddConstraint(
            model_name='college',
            constraint=models.UniqueConstraint(fields=('college_name', 'state_province', 'country'), name='college_alt_key'),
        ),
        migrations.AddConstraint(
            model_name='college',
            constraint=models.UniqueConstraint(fields=('email_domain',), name='email_unique'),
        ),
    ]
