# Generated by Django 4.0.4 on 2023-02-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notetaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('notes_example', models.URLField(blank=True, null=True)),
                ('study_guide_example', models.URLField(blank=True, null=True)),
                ('cheat_sheet_example', models.URLField(blank=True, null=True)),
                ('courses', models.ManyToManyField(to='colleges.course')),
            ],
        ),
    ]
