# Generated by Django 4.0.4 on 2023-02-28 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_alter_course_course_id_alter_course_course_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='college_course_alt_key',
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.department'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('college', 'course_name', 'course_id'), name='college_course_alt_key'),
        ),
    ]
