# Generated by Django 4.0.4 on 2023-02-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_remove_course_college_course_alt_key_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='secondary_course_id_key',
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='college_course_alt_key',
        ),
        migrations.RemoveConstraint(
            model_name='requestcourse',
            name='req_course_alt_key',
        ),
        migrations.RemoveConstraint(
            model_name='requestcourse',
            name='secondary_course_id_key_request_course',
        ),
        migrations.AlterField(
            model_name='requestcourse',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.department'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('college', 'course_id'), name='secondary_course_id_key'),
        ),
        migrations.AddConstraint(
            model_name='requestcourse',
            constraint=models.UniqueConstraint(fields=('college', 'course_id'), name='secondary_course_id_key_request_course'),
        ),
    ]
